### ISSUE TITLE
Should `variable-type` work even if the type of variable is NIL?

### ISSUE THREAD

**Issue by digikar99** [alex-gutev/cl-form-types#7]
On some implementations, `cl-form-types:form-type` fails because `variable-information` of `x` returns `NIL` as the first value (CCL) instead of `:LEXICAL` (SBCL):

```lisp
CL-USER> (cl-form-types::special-form-type 'locally '((declare (type string x)) x) nil)
T ; on CCL; returns STRING as expected on SBCL
```

https://github.com/alex-gutev/cl-form-types/blob/7a68e67abca423e622349ef0ca97b73fa3f6c212/src/form-types.lisp#L555-L580

One way to get the desired behavior could be to avoid checking for `:lexical :special`, but I'm unsure if that leads to other issues, does it?

***

Another issue is, while the SBCL behavior is more preferable, I'm unsure if the first return value should be `:LEXICAL` (it should rather be `NIL` perhaps? Am I missing something?):

```lisp
CL-USER> (cl-environments:variable-information
          'x
          (cl-environments:augment-environment 
           nil
           :declare
           '((type string x))))
:LEXICAL
T
((TYPE . STRING))
```

**Comment by alex-gutev** [comment]
There are two issues here:
1. `variable-information` should return `NIL` in this case since `x` is not declared in any environment nor is it declared as a special variable. The reason `:LEXICAL` is returned on SBCL is due to a bug in cl-environments. SBCL signals an error condition if `augment-environment` is passed a type declaration, in `:declare`, for a variable which is not listed in the `:variable` argument, even if the environment that is being augmented contains a binding (lexical or special) for that variable. My wrapped around `augment-environment` simply extracts all variables listed in `type` declarations and adds them to the `:variable` argument. You can open up an issue in cl-environments if you wish.
2. I'm not sure what would be regarded as the correct behaviour if `variable-information` returns `NIL` but there is type information in the declaration list, since referencing and unbound variable is undefined behaviour, whether there is a type declaration or not.

**Comment by digikar99** [comment]
> referencing an unbound variable is undefined behaviour, whether there is a type declaration or not.

I see, in that case, this looks fine the way it is, save for the but on SBCL. For the form type, one can explicitly `augment-environment` with appropriate variables, and then proceed. Thanks!
